console.log-ok kivevése
vonKotan/Near-Balkan_films pull request #61
Opened 2024-06-28 12:59 UTC by lilihullam

Remélem, hogy jól csináltam és mindent kiszedtem, amit kellett és semmit, amit nem :') köszi, puszi szivik xd

2024-06-30 11:00 UTC, forriM requested changes
Egy két helyre írtam, de ezeket nem te rontottad el csak én felejtettem el mondani.

2024-06-30 11:00 UTC, forriM commented on src/components/AddFavorite.js
> -      console.log(err.message);
Ezt elgelejtettem mondani anno, de ezek amik ilyen cath blokkban vannak ezek szerintem maradjan mert ez csak akkor ír ki ha valami hiba van és ezekből látjuk, hogy mi a hiba. Úgyhogy ezeket tedd vissza légyszi.

2024-06-30 11:00 UTC, forriM commented on src/components/AddFavorite.js
> -      console.log(err.message);
Ezt is

2024-06-30 11:00 UTC, forriM commented on src/hooks/useAddEvent.jsx
> -            console.log(e.message)
ezt is

2024-06-30 11:00 UTC, forriM commented on src/hooks/useAuth.js
> -        imageurl = await uploadImage('profilepictures', userInfo.profilePicture, Date.now(), auth.currentUser.email);
Ezitt nem tudom mért lett töröve, de biztos, hogy ez még kell, csak a console.log-okat szedjük ki belőle.

2024-06-30 11:00 UTC, forriM commented on src/hooks/useAuth.js
> -      console.log(e.message);
Ez is maradhat

2024-06-30 11:00 UTC, forriM commented on src/hooks/useFetchData.js
> -        console.log(e.message);
Ez is

2024-07-01 11:27 UTC, lilihullam commented on src/components/AddFavorite.js
> -      console.log(err.message);
okayyy, on it

2024-07-01 12:49 UTC, lilihullam commented
"overrides": {
    "@svgr/webpack": "$@svgr/webpack"
  },

ezt hozzárakhatom a package.json-hoz? Talán így már fel tudnám tölteni amit csináltam, idk mi a baja, de folyton ezt kapom.

![448618632_462145459900132_8619140226453514416_n](https://github.com/vonKotan/Near-Balkan_films/assets/162151745/e5751d9f-140b-422e-bfb7-dcb98e39508a)

és találtam egy ilyent megoldásnak, hátha: https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert

2024-07-04 09:57 UTC, closed without merging